### ISSUE TITLE
Pure virtual functions

### ISSUE THREAD

**Issue by Skylark13** [Aeva/springheeled-cpp#1]
Hello! 
Good notes! I'm sure they will help many others starting out or who want a refresher.

For the content, IMHO you have oversimplified some things, but in most cases I think that's fine, since it's meant as a quick summary. You may want to change mentions of GC / garbage collection since there is no such thing in C++. Unless you do it yourself. In C++ you allocate memory, then you free it. Calls to new / malloc allocate memory (new also calls the constructor of the type so the object is initialized), and calls to delete / free will free memory (delete also calls the destructor of the type so the object can destroy any resources it owns).

There was one thing that was incorrect (that I saw), and I didn't want to fork, fix and submit a pull request for such a minor change.

You say: "A base class can be left as an “abstract base class” by simply leaving one or more virtual functions as stubs. These are called “pure virtual” functions, since they can’t be statically bound."

It's not clear what you mean by "as stubs", but generally that means the function has an empty body. This is callable, and is not a pure virtual function. A pure virtual function is one that is assigned to 0. like this:

``` C++
virtual void function() { /*nothing here*/ }     // this is a stub
virtual void function() = 0;                     // this is a pure virtual function
```

For a class to be instantiable (so you can create an instance of it on the stack or with new), it has to be a concrete class, i.e. it cannot have any pure virtual functions and it must have implemented all the pure virtual functions of any class it inherits from.

Hope this helps, and again, great work!

**Comment by Aeva** [comment]
Hey, thanks for the feedback!  Sorry for the delay in response, I somehow missed the notification for this and only just saw it.  I've clarified the notes as per your recommendations.

**Comment by Skylark13** [comment]
Great! :thumbsup:
